<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Templates\WelcomeTemplate.html" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Templates\WelcomeTemplate.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Demo_WebAPI_EventAgenda.ApplicationCore\Demo_WebAPI_EventAgenda.ApplicationCore.csproj" />
    <ProjectReference Include="..\Demo_WebAPI_EventAgenda.Domain\Demo_WebAPI_EventAgenda.Domain.csproj" />
  </ItemGroup>

</Project>
